name: 'yarn'
description: 'Install Yarn dependencies'

runs:
  using: 'composite'
  steps:
    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      id: cache-yarn
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install Yarn dependencies
      if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
