name: 'java'
description: 'Install and set up Java, Android SDK, and NDK'

runs:
  using: 'composite'
  steps:
    - name: Write Android signing keys to gradle.properties
      shell: bash
      run: |
        mkdir -p ~/.gradle
        touch ~/.gradle/gradle.properties
        echo "ALYSIUM_UPLOAD_STORE_FILE=${{ secrets.ALYSIUM_UPLOAD_STORE_FILE }}" >> ~/.gradle/gradle.properties
        echo "ALYSIUM_UPLOAD_STORE_PASSWORD=${{ secrets.ALYSIUM_UPLOAD_STORE_PASSWORD }}" >> ~/.gradle/gradle.properties
        echo "ALYSIUM_UPLOAD_KEY_ALIAS=${{ secrets.ALYSIUM_UPLOAD_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
        echo "ALYSIUM_UPLOAD_KEY_PASSWORD=${{ secrets.ALYSIUM_UPLOAD_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties

    - name: Write Android Keystore
      shell: bash
      run: |
        echo "${{ secrets.ANDROID_ENCRYPTED_KEYSTORE }}" | base64 --decode > ./android/app/alysium.keystore

    - name: Write Google Play Upload Key Credentials
      shell: bash
      run: |
        echo "${{ secrets.GOOGLE_PLAY_SERVICE_KEY }}" | base64 --decode > /tmp/google-play-credentials.json
