name: 'pods'
description: 'Install pods'

runs:
  using: 'composite'
  steps:
    - name: Cache CocoaPods dependencies
      uses: actions/cache@v4
      id: cache-cocoapods
      with:
        path: ios/Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}
    - name: Install CocoaPods dependencies
      if: steps.cache-cocoapods.outputs.cache-hit != 'true'
      run: bundle exec pod install
      working-directory: ios
      shell: bash
