import { Dimensions } from 'react-native'

const { height: SCREEN_HEIGHT } = Dimensions.get('window')

// Artist page
const ARTIST_PAGE_NOTCH_HEADER_HEIGHT = 50
const ARTIST_PAGE_MAIN_IMAGE_HEIGHT = SCREEN_HEIGHT * 0.3
const ARTIST_PAGE_TOTAL_HEADER_HEIGHT = ARTIST_PAGE_NOTCH_HEADER_HEIGHT + ARTIST_PAGE_MAIN_IMAGE_HEIGHT

export default {
    ARTIST_PAGE_NOTCH_HEADER_HEIGHT,
    ARTIST_PAGE_MAIN_IMAGE_HEIGHT,
    ARTIST_PAGE_TOTAL_HEADER_HEIGHT
}