name: 'Write Environment Variables'
description: 'Write environment variables to .env.* file'
inputs:
  ENV:
    description: 'ENV environment variable name'
    type: choice
    options:
      - qa
      - demo
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        # Environment name
        echo "ENV=${{ inputs.ENV }}" >> .env.${{ inputs.ENV }}

        # Api url (e.g. https://qa-api.alysium.ninja)
        echo "API_URL=https://${{ inputs.ENV }}-api.alysium.ninja" >> .env.${{ inputs.ENV }}

      shell: bash
