name: 'Write Environment Variables'
description: 'Write environment variables to .env.* file'
inputs:
  ENV:
    description: 'ENV environment variable name'
    type: choice
    options:
      - qa
      - demo
      - prod
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        # Environment name
        echo "ENV=${{ inputs.ENV }}" >> .env.${{ inputs.ENV }}

        # Api url (e.g. https://qa-api.alysium.ninja)
        echo "API_URL=https://api-${{ inputs.ENV }}.alysium.ninja/alysium" >> .env.${{ inputs.ENV }}

        # Images base url (e.g. IMAGES_BASE_URL='https://dev-images.alysium.ninja/')
        echo "IMAGES_BASE_URL=https://${{ inputs.ENV }}-images.alysium.ninja/" >> .env.${{ inputs.ENV }}

      shell: bash
