name: 'ssh-config'
description: 'Configure SSH keys'

inputs:
  match_deploy_key:
    description: 'SSH key for accessing the repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH key for match
      shell: bash
      run: |
        mkdir -p /Users/runner/.ssh
        echo "${{ inputs.match_deploy_key }}" > /Users/runner/.ssh/alysium_match
        chmod 600 /Users/runner/.ssh/alysium_match
        ssh-keyscan github.com >> /Users/runner/.ssh/known_hosts
        echo -e "Host github.com\n  IdentityFile /Users/runner/.ssh/alysium_match\n  IdentitiesOnly yes" > /Users/runner/.ssh/config
