
auth.token=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

defaults.org=alysium
defaults.project=react-native

defaults.url=https://sentry.io/
