require_relative '../tools/get-changelog-notes'
require_relative '../tools/prepare-android-changelog'
require_relative '../tools/utils'
require 'json'

android_metadata_path = './fastlane/metadata/android'
version_code = get_current_build_number_from_package_json

# Sourcemaps (from `yarn generate-sourcemaps`)
# I know that this looks weird, because they actually get generated to "../main.jsbundle"
# and "../main.jsbundle.map" respectively, but actually since we're executing this with
# the `bundle exec` command, the current working directory is the root of the project,
# not the fastlane directory. Just...stop asking questions.
bundle_path = "main.jsbundle"
sourcemap_path = "main.jsbundle.map"

ENVIRONMENT_CONFIG = {
  'dev' => {
    scheme: 'alysium',
    app_identifier: 'io.alysium.dev',
    ipa_filename: 'alysium-dev.ipa'
  },
  'qa' => {
    scheme: 'alysium-qa',
    app_identifier: 'io.alysium.qa',
    ipa_filename: 'alysium-qa.ipa'
  },
  'demo' => {
    scheme: 'alysium-demo',
    app_identifier: 'io.alysium.demo',
    ipa_filename: 'alysium-demo.ipa'
  },
  'prod' => {
    scheme: 'alysium-prod',
    app_identifier: 'io.alysium',
    ipa_filename: 'alysium-prod.ipa'
  }
}

# Function to get environment option by key name and throw an exception if
# the environment name or key does not exist
def get_environment_option(env, key)
    environment = ENVIRONMENT_CONFIG[env]
    if environment.nil?
        UI.user_error!("Environment '#{env}' does not exist")
    end

    option = environment[key]
    if option.nil?
        UI.user_error!("Key '#{key}' does not exist in the '#{ENV['ENVIRONMENT']}' environment")
    end

    return option
end

# Helper method to get version from package.json
def get_version_from_package_json
  package = JSON.parse(File.read('../package.json'))
  return package['version']
end

lane :test_lane do |options|
    # Use this lane to test your Fastfile
    # Be sure to delete whatever you're testing here before committing tho... >_>
    puts 'Test lane'
end

platform :ios do

    lane :build do |options|
        # This lane builds the app and uploads it to TestFlight
        # @param options[:environment] The environment to deploy to

        # Configure ci environment
        # You will run into this error if you don't set up the CI environment:
        #   Missing password for user example@gmail.com, and running in non-interactive shell
        # Basically this command sets up the keychain for the CI environment
        setup_ci

        # Make sure match is set up correctly for the testflight deployment
        match(
            type: 'appstore',
            readonly: true,
            clone_branch_directly: true,
            app_identifier: get_environment_option(options[:environment], :app_identifier)
        )

        # Build
        gym(
            scheme: get_environment_option(options[:environment], :scheme),
            export_method: 'app-store',
            workspace: './ios/alysium.xcworkspace',
            xcconfig: './CustomIOSBuild.xcconfig',
            output_directory: './ios/build',
            output_name: get_environment_option(options[:environment], :scheme) + '.ipa',
            silent: true,
            export_xcargs: '-jobs $(sysctl -n hw.ncpu)'
        )

        # Generate the React Native bundle and sourcemap
        scheme = get_environment_option(options[:environment], :scheme)
      
        # Upload sourcemaps to Sentry
        upload_sentry_sourcemaps(
            environment: options[:environment],
            build_number: options[:build_number]
        )
    end

    # Build and ship to testflight
    lane :deploy do |options|
        # This lane uploads the artifact to TestFlight
        # @param options[:environment] The environment to deploy to

        # Appstoreconnect API key for pilot to upload to TestFlight
        api_key = app_store_connect_api_key(
            key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
            issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
            key_content: Base64.decode64(ENV['APP_STORE_CONNECT_API_KEY_CONTENT'])
        )

        # Get the latest changelog
        changelog = get_latest_changelog

        # Upload to TestFlight
        pilot(
            ipa: './ios/build/' + get_environment_option(options[:environment], :ipa_filename),
            skip_submission: true,
            skip_waiting_for_build_processing: true,
            username: 'aymather@gmail.com',
            app_identifier: get_environment_option(options[:environment], :app_identifier),
            distribute_external: false,
            changelog: changelog,
            beta_app_feedback_email: 'aymather@gmail.com',
            beta_app_description: 'Build Live Music',
            groups: []
        )
    end

    lane :upload_sentry_sourcemaps do |options|
        environment = options[:environment]
        version = get_version_from_package_json
        build_number = options[:build_number] || version_code
        app_identifier = get_environment_option(environment, :app_identifier)
        
        release_version = "#{app_identifier}@#{version}+#{build_number}"
        dist = "#{environment || 'prod'}-#{version}"
        
        UI.message("Uploading Sentry sourcemaps for iOS: Release=#{release_version}, Dist=#{dist}")
      
        # Debug: Verify the files exist
        UI.message("Checking for bundle at: #{bundle_path}")
        UI.message("Checking for sourcemap at: #{sourcemap_path}")
        sh("ls -la #{bundle_path}") rescue UI.message("Bundle file not found!")
        sh("ls -la #{sourcemap_path}") rescue UI.message("Sourcemap file not found!")
      
        sentry_create_release(
          auth_token: ENV['SENTRY_AUTH_TOKEN'],
          org_slug: ENV['SENTRY_ORG'],
          project_slug: ENV['SENTRY_PROJECT'],
          version: release_version,
          finalize: false
        )
        
        sentry_set_commits(
          auth_token: ENV['SENTRY_AUTH_TOKEN'],
          org_slug: ENV['SENTRY_ORG'],
          project_slug: ENV['SENTRY_PROJECT'],
          version: release_version,
          auto: true
        )
        
        sentry_debug_files_upload(
          auth_token: ENV['SENTRY_AUTH_TOKEN'],
          org_slug: ENV['SENTRY_ORG'],
          project_slug: ENV['SENTRY_PROJECT'],
          path: '../ios/build/Build/Products',
          include_sources: true
        )
        
        # Upload the specific bundle and sourcemap files
        sentry_upload_sourcemap(
          auth_token: ENV['SENTRY_AUTH_TOKEN'],
          org_slug: ENV['SENTRY_ORG'],
          project_slug: ENV['SENTRY_PROJECT'],
          app_identifier: app_identifier,
          version: release_version,
          dist: dist,
          sourcemap: [bundle_path, sourcemap_path], # Pass both files as an array
          rewrite: true
        )
        
        sentry_finalize_release(
          auth_token: ENV['SENTRY_AUTH_TOKEN'],
          org_slug: ENV['SENTRY_ORG'],
          project_slug: ENV['SENTRY_PROJECT'],
          version: release_version
        )
    end

end

platform :android do

    lane :build do |options|
        # This lane builds the app
        # @param options[:env] The environment to build for

        ENV['ENVFILE'] = '.env.' + options[:env]

        prepare_android_changelog

        gradle(
            task: 'clean',
            project_dir: './android',
            gradle_path: './gradlew'
        )

        gradle(
            task: 'bundle',
            project_dir: './android',
            gradle_path: './gradlew',
            flavor: options[:env],
            build_type: 'Release'
        )

        # After the build completes, add:
        upload_android_sentry_sourcemaps(
            env: options[:env],
            build_number: options[:build_number]
        )
    end

    lane :deploy do |options|
        # This lane uploads the artifact to TestFlight
        # @param options[:env] The flavor to upload

        upload_to_play_store(
            track: 'internal',
            aab: "./android/app/build/outputs/bundle/#{options[:env]}Release/app-#{options[:env]}-release.aab",
            metadata_path: android_metadata_path,
            version_code: version_code
        )
    end

    # Updated lane for Android Sentry sourcemaps using the plugin
    lane :upload_android_sentry_sourcemaps do |options|
      environment = options[:env]
      version = get_version_from_package_json
      build_number = options[:build_number] || version_code
      
      # For Android, the app identifier depends on the environment
      app_identifier_suffix = environment == 'prod' ? '' : ".#{environment}"
      app_identifier = "io.alysium#{app_identifier_suffix}"
      
      # Match format from App.tsx: <BUNDLE ID>@<RELEASE SEMVER>+<BUILD NUMBER>
      release_version = "#{app_identifier}@#{version}+#{build_number}"
      dist = "#{environment || 'prod'}-#{version}"
      
      UI.message("Uploading Sentry sourcemaps for Android: Release=#{release_version}, Dist=#{dist}")
      
      # Create a new release in Sentry
      sentry_create_release(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: ENV['SENTRY_ORG'],
        project_slug: ENV['SENTRY_PROJECT'],
        version: release_version,
        finalize: false # We'll finalize after uploading sourcemaps
      )
      
      # Associate commits with the release
      sentry_set_commits(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: ENV['SENTRY_ORG'],
        project_slug: ENV['SENTRY_PROJECT'],
        version: release_version,
        auto: true
      )
      
      # Upload sourcemaps for React Native
      sentry_upload_sourcemap(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: ENV['SENTRY_ORG'],
        project_slug: ENV['SENTRY_PROJECT'],
        version: release_version,
        dist: dist,
        sourcemap: "../android/app/build/generated/assets/react/#{environment}Release",
        rewrite: true,
        wait: true
      )
      
      # Upload Proguard mapping files for Android
      sentry_upload_proguard(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: ENV['SENTRY_ORG'],
        project_slug: ENV['SENTRY_PROJECT'],
        android_manifest_path: "../android/app/build/intermediates/merged_manifests/#{environment}Release/AndroidManifest.xml",
        mapping_path: "../android/app/build/outputs/mapping/#{environment}Release/mapping.txt"
      )
      
      # Finalize the release
      sentry_finalize_release(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: ENV['SENTRY_ORG'],
        project_slug: ENV['SENTRY_PROJECT'],
        version: release_version
      )
    end

end

