name: Alysium Android Testflight

on:
  push:
    branches:
      - workflow

jobs:
  build-testflight:

    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:

    # Init
    - name: Checkout the repository
      uses: actions/checkout@v4

    # Write the env file
    - name: Write .env file
      uses: ./.github/actions/write-env-vars
      with:
        envtype: 'staging'
        API_URL: ${{ env.API_URL_STAGING }}
        ENV: ${{ env.ENV_STAGING }}

    # Set up Node.js
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'

    # yarn
    - name: Install yarn dependencies
      uses: ./.github/actions/yarn

    # gems
    - name: Install gem dependencies
      uses: ./.github/actions/gems

    # java
    - name: Set up Java
      uses: ./.github/actions/java

    # android
    - name: Build android
      run: bundle exec fastlane android test_build
      working-directory: fastlane
