name: Alysium Android Testflight

on:
  push:
    branches:
      - workflow

jobs:
  build-testflight:

    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:

    # Init
    - name: Checkout the repository
      uses: actions/checkout@v4

    # Write the env file
    - name: Write .env file
      uses: ./.github/actions/write-env-vars
      with:
        envtype: 'staging'
        API_URL: ${{ env.API_URL_STAGING }}
        ENV: ${{ env.ENV_STAGING }}

    # Set up Node.js
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'

    # yarn
    - name: Install yarn dependencies
      uses: ./.github/actions/yarn

    # gems
    - name: Install gem dependencies
      uses: ./.github/actions/gems

    # java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Cache Android SDK and NDK
      id: cache-android
      uses: actions/cache@v4
      with:
        path: |
          /Users/runner/Library/Android/sdk/build-tools/33.0.0
          /Users/runner/Library/Android/sdk/platforms/android-33
          /Users/runner/Library/Android/sdk/ndk/23.1.7779620
        key: ${{ runner.os }}-android-sdk-33-ndk-23.1.7779620
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Install Android Build Tools and SDKs
      if: steps.cache-android.outputs.cache-hit != 'true'
      run: |
        yes | sdkmanager "build-tools;33.0.0" "platforms;android-33" "ndk;23.1.7779620"

    # android credentials
    - name: Write Android signing keys to gradle.properties
      uses: ./.github/actions/android-credentials
      with:
        ALYSIUM_UPLOAD_STORE_FILE: ${{ secrets.ALYSIUM_UPLOAD_STORE_FILE }}
        ALYSIUM_UPLOAD_STORE_PASSWORD: ${{ secrets.ALYSIUM_UPLOAD_STORE_PASSWORD }}
        ALYSIUM_UPLOAD_KEY_ALIAS: ${{ secrets.ALYSIUM_UPLOAD_KEY_ALIAS }}
        ALYSIUM_UPLOAD_KEY_PASSWORD: ${{ secrets.ALYSIUM_UPLOAD_KEY_PASSWORD }}
        ANDROID_ENCRYPTED_KEYSTORE: ${{ secrets.ANDROID_ENCRYPTED_KEYSTORE }}
        GOOGLE_PLAY_SERVICE_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_KEY }}

    # android
    - name: Build android
      run: bundle exec fastlane android test_build
      working-directory: fastlane
