name: Hello World Workflow

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.0.0' # Specify your Node.js version here

    - name: Install dependencies
      run: yarn install
      run: bundle install

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2' # Specify your Ruby version here

    - name: Run a one-line script
      run: echo Hello, world! ${{ secrets.MATCH_PASSWORD }}
    
    - name: Print out the current directory
      run: pwd

    - name: List the files in the repository
      run: ls -la
