name: Hello World Workflow

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    # Set up node.js
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.4.0' # Specify your Node.js version here

    # Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2' # Specify your Ruby version here

    # Set up java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Install Android Build Tools and SDKs
      run: |
        yes | sdkmanager "build-tools;33.0.0" "platforms;android-33" "ndk;23.1.7779620"

    # Install yarn/restore cache
    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      id: cache-yarn
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install Yarn dependencies
      if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: yarn install

    # Install ruby/restore cache
    - name: Cache Ruby dependencies
      uses: actions/cache@v3
      id: cache-ruby
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
    - name: Install ruby dependencies
      run: bundle install

    # Install pods/restore cache
    - name: Cache CocoaPods dependencies
      uses: actions/cache@v3
      id: cache-cocoapods
      with:
        path: ios/Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}
    - name: Install CocoaPods dependencies
      if: steps.cache-cocoapods.outputs.cache-hit != 'true'
      run: bundle exec pod install
      working-directory: ios

    - name: Run a one-line script
      run: echo Hello, world! ${{ secrets.MATCH_PASSWORD }}
    
    - name: Print out the current directory
      run: pwd

    - name: List the files in the repository
      run: ls -la
