name: Hello World Workflow

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo Hello, world! ${{ secrets.MATCH_PASSWORD }}
    
    - name: Print out the current directory
      run: pwd

    - name: List the files in the repository
      run: ls -la
