name: Alysium Build & Deploy iOS

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - qa
          - demo
      deploy:
        description: 'Whether to deploy the build'
        required: false
        type: boolean
        default: false
      save:
        description: 'Whether to save the build as an artifact'
        required: false
        type: boolean
        default: false

jobs:
  build-and-deploy:
    runs-on: macos-13

    steps:
    
    # Init
    - name: Checkout the repository # repo
      uses: actions/checkout@v4

    # Print out all the input arguments
    - name: Print out the input arguments
      run: |
        echo "Environment: ${{ github.event.inputs.env }}"
        echo "Deploy: ${{ github.event.inputs.deploy }}"
        echo "Save: ${{ github.event.inputs.save }}"
    